title: '<a href="https://www.filamentgroup.com" class="project-logo">Filament Group</a> <span>Modal</span>'
description: A simple, accessible modal dialog web component
theme: jekyll-theme-cayman
show_downloads: true
